@hostname = http://localhost:4000/api/v1
#@hostname = https://demo-smatera.bellyeah.jp/api/v1
# @hostname = https://pr-api.onrender.com/api/v1

@endpoint = /guest/auth
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0Zjg3YmFiZGY5NzFmZGYxZWQ4NDNiOCIsImlhdCI6MTY5NDQ5NzUxNSwiZXhwIjoxNjk3MDg5NTE1fQ.qLj84m8K81nqT82W0nDUeAfZIfuh7J64bHWHHPr2Tzc

### LOGIN USER
POST {{hostname}}{{endpoint}}/login
content-type: application/json
Authorization: {{token}}

{
	"email": "pyduvyny@mailinator.com",
	"password": "password"
}

### VERIFY EMAIL AND SEND CODE
POST {{hostname}}{{endpoint}}/loginEmail
content-type: application/json
Authorization: {{token}}

{
	"email": "pyduvyny@mailinator.com"
}

### LOGIN USING CODE
POST {{hostname}}{{endpoint}}/loginCode
content-type: application/json
Authorization: {{token}}

{
	"code": "990857",
	"codeToken": "e002360668accc10979394788898d717ddad4e5881911f7cb65ef19a6b0f22bc"
}

### GET SELF
GET {{hostname}}{{endpoint}}/me
Authorization: {{token}}

### REGISTER USER
POST {{hostname}}{{endpoint}}/register
content-type: application/json
Authorization: {{token}}

{
	"email": "ez2@mil.com",
	"password": "password",
	"firstName": "ez",
	"lastName": "mil",
	"mobileNumber": "09999999",
	"passwordConfirm": "password"
}

### UPDATE SELF
PATCH {{hostname}}{{endpoint}}/updateMe
content-type: application/json
Authorization: {{token}}

{
	"name": "Ez t",
	"email": "pyduvyny@mailinator.com"
}

### UPDATE PASSWORD
PATCH {{hostname}}{{endpoint}}/update_password
content-type: application/json
Authorization: {{token}}

{

	"password": "password",
	"password_confirm": "password",
	"new_password": "password"
}

### FORGOT PASSWORD
# this request emails the user with the token and link to reset the password 
# use the token to reset the password via api request
POST {{hostname}}{{endpoint}}/forgot_password
content-type: application/json
Authorization: {{token}}

{
	"email": "ez@mil.com"
}


### RESET PASSWORD
PATCH {{hostname}}{{endpoint}}/reset_password/897faf708db046afadfc51a77e309c25b649d00e72e88d879503a4d82c28bb4a
content-type: application/json
Authorization: {{token}}

{
	"password": "password",
	"password_confirm": "password"
}

### GET ORDERS
GET {{hostname}}{{endpoint}}/orders
Authorization: {{token}}

### GET WISHLIST
GET {{hostname}}{{endpoint}}/wishlist
Authorization: {{token}}

### UPDATE WISHLIST
PATCH {{hostname}}{{endpoint}}/update/wishlist
content-type: application/json
Authorization: {{token}}

{ "wishList": "62cd28e49d88175f998615f5" }

### UPDATE WISHLIST
DELETE {{hostname}}{{endpoint}}/delete/wishlist/62cd28e49d88175f998615f5
content-type: application/json
Authorization: {{token}}